### ISSUE TITLE
[4.1.0 regression] error TS2307: Cannot find module './adjacencyGraphs.json' or its corresponding type declarations.

### ISSUE THREAD

**Issue by andersk** [zxcvbn-ts/zxcvbn#319]
In `@zxcvbn-ts/language-common` 4.1.0, `dist/adjacencyGraphs.json.cjs` and `dist/adjacencyGraphs.json.mjs` have no corresponding `.d.cts` and `.d.mts` declarations, leading to this error:

```console
$ npm i @zxcvbn-ts/language-common typescript
$ >test.ts echo 'import * as zxcvbnCommonPackage from "@zxcvbn-ts/language-common";'
$ npx tsc test.ts
node_modules/@zxcvbn-ts/language-common/dist/index.d.ts:1:29 - error TS2307: Cannot find module './adjacencyGraphs.json' or its corresponding type declarations.

1 import adjacencyGraphs from './adjacencyGraphs.json';
                              ~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/@zxcvbn-ts/language-common/dist/index.d.ts:1
```

Fails in `@zxcvbn-ts/language-common` 4.1.0; worked in 3.0.4.

Related:

- #200

**Comment by andersk** [comment]
This was broken by 0c84a11e821e299d311e61458111fbc64318705b (cc @MrWook), which incorrectly reverted the previous fix #201.

**Comment by andersk** [comment]
This could have been [caught](https://arethetypeswrong.github.io/?p=%40zxcvbn-ts%2Flanguage-common%404.1.0) by running [`@arethetypeswrong/cli`](https://www.npmjs.com/package/@arethetypeswrong/cli) in CI.

**Comment by MrWook** [comment]
Hey, thank you for the report.

It's actually not the commit but the regeneration of the file, as in the previous fix it was not fixed in the generator.
I will check out [@arethetypeswrong/cli](https://www.npmjs.com/package/@arethetypeswrong/cli)

**Comment by MrWook** [comment]
@andersk thanks again for showing me [@arethetypeswrong/cli](https://www.npmjs.com/package/@arethetypeswrong/cli).
Looks great even if its not for newer node version but it works great anyway.

I added it to the workflow 👍 https://github.com/zxcvbn-ts/zxcvbn/pull/321
